blank_issues_enabled: false
contact_links:
  - name: "Diskussionen"
    url: "https://github.com/benjamin-schmid/SchulnetzREvanced/discussions"
    about: "FÃ¼r allgemeinen Austausch und Community-Fragen."
